fix: main branch test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,8 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
+branch="$(git rev-parse --abbrev-ref HEAD)"
 
-# TODO: enable later
-#npm run eslint
-#npm run typecheck
-#npm run test
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
